# Site settings
author: Christian Jacobs
title: Christian Jacobs
description: Personal website of Christian Jacobs.
keywords: christian jacobs, research, computational science, computational fluid dynamics, research data management, software, teaching, amateur radio, ham radio
baseurl: "/" # The subpath of your site, e.g. /blog/
url: "https://christianjacobs.uk" # The base hostname & protocol for your site. Use "http://localhost:4000" for local builds.

twitter_username: ctjacobs_uk
github_username:  ctjacobs
linkedin_id: ctjacobs

# Build settings
markdown: kramdown
